library: papier.sqlite
directory: ~/papier
log: papier.log

import:
  copy: yes
  delete: no
  ocr: yes
  overwrite_text: no
  overwrite_tags: no
  autotag: yes
  set:
    tagger: papier
  require:
    - date
    - lang
    - emmitter

autotag:
  # which plugin should be used for which tag
  priority:
    date: date

#plugins: []
plugins:
  - date
  - date_spacy
  - lang
  - emmitter
  - read_tags

organize:
  - when:
    - emmitter
    - date
    - subject
    path: 'misc/{{ emmitter }} - {{ date }} - {{ subject }}.pdf'
