library: papier.sqlite
directory: ~/papier
log: papier.log
dry_run: False
#log: "-"

import:
  copy: yes
  delete: no
  modify: no
  ocr: empty
  redo_ocr: no
  autotag: yes
  set:
    tagger: papier
  require:
    - date
    - lang
    - emmitter

autotag:
  # which plugin should be used for which tag
  priority:
    date: date
  # confidence required for the tagging to be considered successful
  accept:
    date: .90
    lang: .90
    emmitter: .70

#plugins: [example]
plugins:
  - date
  - date_spacy
  - lang
  - emmitter
  - read_tags
  - set_tags

path:
  basename: '{{ [business, date, subject] | reject("==", "") | join(" - ") }}.pdf'
