library: papier.sqlite
directory: ~/papier
log: papier.log

import:
  copy: yes
  delete: no
  modify: no
  ocr: yes
  redo_ocr: no
  autotag: yes
  set_tag:
    tagged_by: papier

match:
  threshold:
    author: .95
    date: .95
    title: .75

#plugins: [example]
plugins: []

path:
  basename: '{{ [business, date, subject] | reject("==", "") | join(" - ") }}.pdf'
