library: papier.sqlite
directory: ~/papier
log: papier.log

import:
  copy: yes
  move: no
  write: no
  ocr: no
  redo_ocr: no
  autotag: yes

#plugins: [example]
plugins: []

path:
  basename: '{{ [business, date, subject] | reject("==", "") | join(" - ") }}.pdf'
